### ISSUE TITLE
Handle slurp cancellation

### ISSUE THREAD

**Issue by VincentCordobes** [soywod/dotfiles#1]
When slurp selection  is cancelled (by pressing `esc`)  _wf-recorder_ gets an invalid `-g` and **fallsback to recording the whole screen**

https://github.com/soywod/dotfiles/blob/bf99986541d2650a853618a93ff33834d6aa6166/capture/selection-record.sh#L7
You might want to handle slurp cancellation like so:
```sh
  geom=$(slurp)

  if [ -z "$geom" ]; then
    exit
  fi

  wf-recorder -g "$geom" -f "$file"
```

**Comment by soywod** [comment]
Thanks!
